language: cpp
dist: xenial
compiler: gcc
script: 
     - mkdir -p build
     - cd build
     - cmake -D-DCMAKE_INSTALL_PREFIX=./../ ..
     - make
     - make install
     - cd ..
     - export PATH=PATH:$PATH
     - py.test
