language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: true
      compiler: gcc
      addons:
       apt:
         packages:
           - cmake
           - sqlite3
           - g++
           - python-pytest

     
script:
     - ls -l /usr/local/opt/sqlite
     - export CMAKE_PREFIX_PATH=$CMAKE_PREFIX_PATH:/usr/local/opt/sqlite
     - mkdir -p build
     - cd build
     - cmake -D-DCMAKE_INSTALL_PREFIX=./../ -DSQLite_DIR="/usr/local/opt/sqlite"  ..
     - make
     - make install
     - cd ..
     - export PATH=$PATH:./bin
     - py.test
