language: nix

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      sudo: required

    - os: linux
      dist: trusty
      compiler: gcc
      sudo: required
      
script:
     - nix-shell -A test shell.nix --run 'mkdir -p build && cd build && cmake .. && make && export PATH=$PATH:$(pwd) && cd .. && py.test'
     - nix-shell -A test shell.nix --run 'mkdir -p build && cd build && cmake .. && make && export PATH=$PATH:$(pwd) && cd .. && py.test'
