
matrix:
  include:
    - language: nix
      os: linux
      dist: xenial
      compiler: gcc
      sudo: required
      script: 
        - nix-shell -A test shell.nix --run 'mkdir -p build && cd build && cmake .. && make && sudo make install && cd .. && py.test'

    - language: cpp
      os: linux
      dist: trusty
      compiler: gcc
      sudo: required
      addons:
       apt:
         packages:
           - cmake
           - g++
           - python3
           - python3-pytest
      install:
        mkdir -p build && cd build && cmake .. && make && sudo make install && cd .. && ./install.sh && . ~/.bashrc

script:
    # Run system tests
    - py.test-3
    
    # Check hm installation
    - source tests/test_interface.sh
