language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: gcc
      sudo: required
      addons:
       apt:
         packages:
           - cmake
           - sqlite3
           - libsqlite3-dev
           - g++
           - python3
           - python3-pytest

install:
     - mkdir cmake-dist && curl -sfSL https://github.com/Kitware/CMake/releases/download/v3.14.5/cmake-3.14.5-Linux-x86_64.tar.gz | tar --strip-components=1 -C cmake-dist -xz && export PATH=$PWD/cmake-dist/bin:$PATH
     
script:
     - mkdir -p build
     - cd build
     - cmake ..
     - make
     - sudo make install
     - cd ..
     - py.test-3
