language: nix

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
      sudo: required

script:
     - nix-shell -A test shell.nix --run "mkdir -p build && cd build && cmake .. && make && sudo make install && cd .. && py.test"
