language: cpp

matrix:
  include:
    - os: linux
      dist: xenial
      sudo: true
      compiler: gcc
      addons:
       apt:
         packages:
           - cmake
           - sqlite3
           - g++
           - python-pytest

     
script: 
     - mkdir -p build
     - cd build
     - cmake -D-DCMAKE_INSTALL_PREFIX=./../ ..
     - make
     - make install
     - cd ..
     - export PATH=PATH:$PATH
     - py.test
