name: Build

defaults:
  run:
    shell: bash
    
on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  build:
    name: ubuntu-build-and-test
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install -r requirements.txt
    
    - name: Make hm-db
      run: |
        mkdir -p build && cd build 
        cmake .. && make
        
    - name: Run hm-db tests
      run: |
        export PATH=$PATH:`pwd`/build/src/
        hm-db --version
        py.test
        
    - name: Check python package
      run: |
        HISTFILE=.bash_history
        set -o history        
        pip install .
        hm-init --home `pwd`
        . `pwd`/configuration
        py.test
        echo +++++++++++++ System tests
        . tests/release/prepare_history.sh
        . tests/release/check_history.sh        
        echo +++++++++++++ Cram test
        cram -v --shell=bash tests/release/test_interface.t
