name: Build

defaults:
  run:
    shell: bash
    
on:
  push:
    branches: [ "develop", "master" ]
  pull_request:
    branches: [ "develop", "master" ]

jobs:
  build:
    name: ubuntu-build-and-test
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install -r requirements.txt
    
    - name: Make hm-db
      run: |
        mkdir -p build && cd build 
        cmake .. && make
        
    - name: Run hm-db tests
      run: |
        export PATH=$PATH:`pwd`/build/src/
        hm-db --version
        py.test
        
    - name: Check python package
      run: |
        pip install .
        hm-init bashrc --home `pwd`
        . bashrc
        py.test
        cat bashrc
        echo +++++++++++++
        echo hm-db $hm_history_db parse $hm_history_tmp $separator
        hm-db $hm_history_db parse $hm_history_tmp $separator
        echo TMPFILE=$(mktemp extracted_history.XXXXXXXXXX)
        TMPFILE=$(mktemp extracted_history.XXXXXXXXXX)
        echo hm-db $hm_history_db select $hm_session_id $(echo $ARGS)
        hm-db $hm_history_db select $hm_session_id $(echo $ARGS) > $TMPFILE
        echo hm "$*"
        echo --------------
        hm .
        . tests/release/prepare_history.sh
        echo $test_path
        echo $test_command
        hm -h
        hm .
        echo +++++++++++++
        . tests/release/check_history.sh        
